[project]
name = "cc-agent"
version = "0.1.0"
description = "CC Agent: 基于 agentscope 的前后端分离智能体应用"
readme = "README.md"
authors = [
    { name = "chenrb", email = "crbxyx@foxmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "agentscope[channel,full,models,service,storage-redis,storage-s3,storage-sql,tools,workspace]",
    "aiosqlite>=0.22.1",
    "python-dotenv>=1.2.2",
]

[tool.uv.sources]
agentscope = { path = "./agentscope", editable = true }
